apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: victorwasonga/my-app:6afc96ec266817aeaf127824344d7208e1418274
        ports:
        - containerPort: 3000
