apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: victorwasonga/my-app:ffec61475888be5258eda7f3f8dd1030800a72ff
        ports:
        - containerPort: 3000
