apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: victorwasonga/my-app:b53736b355bae940d9f07bd9a3dbaeaebda2f2b5
        ports:
        - containerPort: 3000
