apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: victorwasonga/my-app:e13b90d803fef5c60f8537ab3b850373e46e9d21
        ports:
        - containerPort: 3000
